config/routes.rb
# == Route Map
#
#                   Prefix Verb   URI Pattern                          Controller#Action
#         new_user_session GET    /users/sign_in(.:format)             devise/sessions#new
#             user_session POST   /users/sign_in(.:format)             devise/sessions#create
#     destroy_user_session DELETE /users/sign_out(.:format)            devise/sessions#destroy
#            user_password POST   /users/password(.:format)            devise/passwords#create
#        new_user_password GET    /users/password/new(.:format)        devise/passwords#new
#       edit_user_password GET    /users/password/edit(.:format)       devise/passwords#edit
#                          PATCH  /users/password(.:format)            devise/passwords#update
#                          PUT    /users/password(.:format)            devise/passwords#update
# cancel_user_registration GET    /users/cancel(.:format)              registrations#cancel
#        user_registration POST   /users(.:format)                     registrations#create
#    new_user_registration GET    /users/sign_up(.:format)             registrations#new
#   edit_user_registration GET    /users/edit(.:format)                registrations#edit
#                          PATCH  /users(.:format)                     registrations#update
#                          PUT    /users(.:format)                     registrations#update
#                          DELETE /users(.:format)                     registrations#destroy
#   accept_user_invitation GET    /users/invitation/accept(.:format)   invitations#edit
#   remove_user_invitation GET    /users/invitation/remove(.:format)   invitations#destroy
#          user_invitation POST   /users/invitation(.:format)          invitations#create
#      new_user_invitation GET    /users/invitation/new(.:format)      invitations#new
#                          PATCH  /users/invitation(.:format)          invitations#update
#                          PUT    /users/invitation(.:format)          invitations#update
#                directory GET    /directory(.:format)                 profiles#index
#              admin_index GET    /admin/index(.:format)               admin#index
#             admin_update PATCH  /admin/update(.:format)              admin#update
#            admin_destroy DELETE /admin/destroy(.:format)             admin#destroy
#          schedules_index GET    /schedules/index(.:format)           schedules#index
#           schedules_test GET    /schedules/test(.:format)            schedules#test
#     create_slots_mentors POST   /mentors/create_slots(.:format)      mentors#create_slots
#     destroy_slots_mentor DELETE /mentors/:id/destroy_slots(.:format) mentors#destroy_slots
#      update_slots_mentor PATCH  /mentors/:id/update_slots(.:format)  mentors#update_slots
#     release_slots_mentor PATCH  /mentors/:id/release_slots(.:format) mentors#release_slots
#                  mentors GET    /mentors(.:format)                   mentors#index
#                          POST   /mentors(.:format)                   mentors#create
#               new_mentor GET    /mentors/new(.:format)               mentors#new
#              edit_mentor GET    /mentors/:id/edit(.:format)          mentors#edit
#                   mentor GET    /mentors/:id(.:format)               mentors#show
#                          PATCH  /mentors/:id(.:format)               mentors#update
#                          PUT    /mentors/:id(.:format)               mentors#update
#                          DELETE /mentors/:id(.:format)               mentors#destroy
#             hiring_posts GET    /posts/hiring(.:format)              posts#hiring
#            promote_posts GET    /posts/promote(.:format)             posts#promote
#             launch_posts GET    /posts/launch(.:format)              posts#launch
#              tools_posts GET    /posts/tools(.:format)               posts#tools
#      request_thing_posts GET    /posts/request_thing(.:format)       posts#request_thing
#              event_posts GET    /posts/event(.:format)               posts#event
#                    posts GET    /posts(.:format)                     posts#index
#                          POST   /posts(.:format)                     posts#create
#                 new_post GET    /posts/new(.:format)                 posts#new
#                edit_post GET    /posts/:id/edit(.:format)            posts#edit
#                     post GET    /posts/:id(.:format)                 posts#show
#                          PATCH  /posts/:id(.:format)                 posts#update
#                          PUT    /posts/:id(.:format)                 posts#update
#                          DELETE /posts/:id(.:format)                 posts#destroy
#              sort_skills POST   /skills/sort(.:format)               skills#sort
#                   skills GET    /skills(.:format)                    skills#index
#                          POST   /skills(.:format)                    skills#create
#                new_skill GET    /skills/new(.:format)                skills#new
#               edit_skill GET    /skills/:id/edit(.:format)           skills#edit
#                    skill GET    /skills/:id(.:format)                skills#show
#                          PATCH  /skills/:id(.:format)                skills#update
#                          PUT    /skills/:id(.:format)                skills#update
#                          DELETE /skills/:id(.:format)                skills#destroy
#                 profiles GET    /profiles(.:format)                  profiles#index
#                          POST   /profiles(.:format)                  profiles#create
#              new_profile GET    /profiles/new(.:format)              profiles#new
#             edit_profile GET    /profiles/:id/edit(.:format)         profiles#edit
#                  profile GET    /profiles/:id(.:format)              profiles#show
#                          PATCH  /profiles/:id(.:format)              profiles#update
#                          PUT    /profiles/:id(.:format)              profiles#update
#                          DELETE /profiles/:id(.:format)              profiles#destroy
#                 comments GET    /comments(.:format)                  comments#index
#                          POST   /comments(.:format)                  comments#create
#              new_comment GET    /comments/new(.:format)              comments#new
#             edit_comment GET    /comments/:id/edit(.:format)         comments#edit
#                  comment GET    /comments/:id(.:format)              comments#show
#                          PATCH  /comments/:id(.:format)              comments#update
#                          PUT    /comments/:id(.:format)              comments#update
#                          DELETE /comments/:id(.:format)              comments#destroy
#                     root GET    /                                    posts#index
#


Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations', invitations: 'invitations' }

  get 'directory/', to: 'profiles#index'

  get 'admin/index'

  patch 'admin/update'

  delete 'admin/destroy'

  get 'schedules/index'

  get 'schedules/test'

  resources :mentors do
    collection do
      post :create_slots
    end
    member do
      delete :destroy_slots
      patch :update_slots
      patch :release_slots
    end
  end


  resources :posts do
    collection do
      get :hiring
      get :promote
      get :launch
      get :tools
      get :request_thing
      get :event
    end
  end

  resources :skills do
    collection { post :sort }
  end

  resources :profiles
  resources :comments


  root "posts#index"

end

app/models/profile.rb
class Profile < ActiveRecord::Base

  has_attached_file :avatar, :styles => { :medium => "300x300#", :thumb => "100x100#" }, default_url: 'face.jpg'
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  belongs_to :user

  validates :micro_bio, length: { maximum: 140 }

end

# ## Schema Information
#
# Table name: `profiles`
#
# ### Columns
#
# Name                       | Type               | Attributes
# -------------------------- | ------------------ | ---------------------------
# **`id`**                   | `integer`          | `not null, primary key`
# **`user_id`**              | `integer`          |
# **`position`**             | `string(255)`      |
# **`company`**              | `string(255)`      |
# **`phone`**                | `string(255)`      |
# **`micro_bio`**            | `string(255)`      |
# **`linked_in`**            | `string(255)`      |
# **`twitter`**              | `string(255)`      |
# **`dribble`**              | `string(255)`      |
# **`behance`**              | `string(255)`      |
# **`codepen`**              | `string(255)`      |
# **`github`**               | `string(255)`      |
# **`created_at`**           | `datetime`         |
# **`updated_at`**           | `datetime`         |
# **`avatar_file_name`**     | `string(255)`      |
# **`avatar_content_type`**  | `string(255)`      |
# **`avatar_file_size`**     | `integer`          |
# **`avatar_updated_at`**    | `datetime`         |
#
# ### Indexes
#
# * `index_profiles_on_user_id`:
#     * **`user_id`**
#

app/models/skill.rb
class Skill < ActiveRecord::Base

  has_and_belongs_to_many :users

  validates_uniqueness_of :skill_name
  
end

# ## Schema Information
#
# Table name: `skills`
#
# ### Columns
#
# Name              | Type               | Attributes
# ----------------- | ------------------ | ---------------------------
# **`id`**          | `integer`          | `not null, primary key`
# **`skill_name`**  | `string(255)`      |
# **`created_at`**  | `datetime`         |
# **`updated_at`**  | `datetime`         |
# **`position`**    | `integer`          |
#

app/models/user.rb
class User < ActiveRecord::Base
  include ActiveModel::Validations
  validates_with StripeValidator
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  acts_as_mentionable

  after_create :create_profile
  has_many :comments, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :sheets, dependent: :destroy
  has_many :slots #don't destroy but definitely will remove the id from the slot
  has_and_belongs_to_many :skills
  has_one :profile, dependent: :destroy

  ROLES = %i[member mentor admin locked]


  def create_profile
  	self.build_profile
  	self.profile.save
  end

  def self.check_stripe_for_email(email)
    stripe_customers = Stripe::Customer.all
    emails = stripe_customers[:data].collect { |customer| customer[:email] }
    emails.include?(email)
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
before_action :authenticate_user!


  def index
    authorize! :read, Profile
  	@users = User.order('last_name') 
  	@skills = Skill.order("position")
  end

  def show

    authorize! :read, Profile
    @user = User.find(params[:id])
    @skills = Skill.order('id')
    @posts = Post.where({ user_id: params[:id]}).order("posts.created_at DESC")
    @comments = Comment.order("comments.created_at ASC")  
  end


  def edit
    @profile = current_user.profile
    authorize! :manage, @profile
    @skills = Skill.order('position')
  end

  def update
      @profile = current_user.profile  
      authorize! :manage, @profile
  	  @profile.update(profile_params)
      skill_array = params[:user][:skill_ids].to_a
      skill_array.each_with_index do |s, i|
        skill_array[i] = s.to_i unless skill_array[i].blank?
      end
        if current_user.update_attributes(skill_ids: params[:user][:skill_ids])
          redirect_to directory_path
        else
          redirect_to edit_profile_path
        end
  end


  private

	# Use strong_parameters for attribute whitelisting
	# Be sure to update your create() and update() controller methods.

	def profile_params
	  params.require(:profile).permit(:avatar, :position, :company, :phone, :micro_bio, :linked_in, :twitter, :dribble, :behance, :codepen, :github, :user
    )

	end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_profile.html.erb
<% @users.each do |user| %>
	<div class="profile-entry">

			<div class="profile-image-div">
				<%= image_tag user.profile.avatar.url(:medium), size: "125x125" %>

			</div>

		<div class="profile-text">
			<h3 class = "title"> <%= link_to user.first_name + " " + user.last_name, profile_path(user.id) if user.first_name && user.last_name %> </h3>
			<% if !user.profile.position.blank? && !user.profile.company.blank? %>
				<p><strong><%= user.profile.position + " @ " + user.profile.company  %></strong></p>
			<% end %>

				<p><a href="mailto:<%= user.email %>"><%= user.email %></a></p>
			<% if !user.profile.phone.blank? %>
				<% number = number_to_phone(user.profile.phone.tr('^0-9', '',).to_i, delimiter: ".") %>
				<p><a href="tel:<%= number %>"><%= number %></a></p>
			<% end %>

			<% if !user.profile.micro_bio.blank? %>
				<p>- <%= user.profile.micro_bio %> -</p>
			<% end %>
		</div>

		<div class="profile-socmed-div">
			<ul class="profile-ul" >
				<% if !user.profile.linked_in.blank? %>
				 	<li class="profile-socmed"><a href="<%= user.profile.linked_in %>" target="_blank"> <i class="fa fa-linkedin fontaweplus"></i></a> </li>
				<% end %>

				<% if !user.profile.twitter.blank? %>
					<li class="profile-socmed"><a href="<%= user.profile.twitter %>" target="_blank"> <i class="fa fa-twitter-square fontaweplus"></i></a> </li>
				<% end %>

				<% if !user.profile.github.blank? %>
					<li class="profile-socmed"><a href="<%= user.profile.github %>" target="_blank"> <i class="fa fa-github-square fontaweplus"></i></a> </li>
				<% end %>

				<% if !user.profile.dribble.blank? %>
					<li class="profile-socmed"><a href="<%= user.profile.dribble %>" target="_blank"> <i class="fa fa-dribbble fontaweplus"></i></a> </li>
				<% end %>

				<% if !user.profile.behance.blank? %>
					<li class="profile-socmed"><a href="<%= user.profile.behance %>" target="_blank"> <i class="fa fa-behance-square fontaweplus"></i></a> </li>
				<% end %>

				<% if !user.profile.codepen.blank? %>
					<li class="profile-socmed"><a href="<%= user.profile.codepen %>" target="_blank"> <i class="fa fa-codepen fontaweplus"></i></a> </li>
				<% end %>
			</ul>
		</div>

		<div class="profile-label-div">
			<ul class="profile-ul">
				<% sorted_skills = user.skills.sort_by { |s| s.position} %>

				<% sorted_skills.each do |skill| %>
					<li class="profile-label"><span class="label label-default2"><%= link_to skill.skill_name, skill_path(skill.id) %></span></li>

				<% end %>
			</ul>
		</div>

	</div>
<% end %>

app/views/profiles/edit.html.erb
<h1 class="profile-update-title">update profile</h1>

<%= form_for @profile, :url => {:action => 'update'}, :html => { :multipart => true, :role => "form", class: "form-horizontal profile-form"  } do |form| %>
  	<div class="form-group">
    	<%= label_tag "Pic", nil, class: "col-sm-2 control-label" %>
    	<div class="col-sm-10">
	  		<%= form.file_field :avatar, class: "form-control" %>
	  	</div>
  	</div>
  	<div class="form-group">
    		<%= label_tag "Company", nil, class: "col-sm-2 control-label" %>
    	<div class="col-sm-10">
			<%= form.text_field :company, class: "form-control"%>
		</div>
	</div> 
  	<div class="form-group">
    		<%= label_tag "Position", nil, class: "col-sm-2 control-label" %>
    	<div class="col-sm-10">
			<%= form.text_field :position, class: "form-control"%>
		</div>
	</div> 
  	<div class="form-group">
    		<%= label_tag "Phone", nil, class: "col-sm-2 control-label" %>
    	<div class="col-sm-10">
			<%= form.text_field :phone, class: "form-control" %>
		</div>
	</div> 
  	<div class="form-group">
    		<%= label_tag "Micro-bio", nil, class: "col-sm-2 control-label" %>
    	<div class="col-sm-10">
			<%= form.text_field :micro_bio, class: "form-control micro-bio-validate"%>
		</div>
	</div> 
  	<div class="form-group">
    		<%= label_tag "Linked_In", nil, class: "col-sm-2 control-label" %>
    	<div class="col-sm-10">
			<%= form.text_field :linked_in, class: "form-control", placeholder: "https://www.linkedin.com/in/yourname"%>
		</div>
	</div> 
  	<div class="form-group">
    		<%= label_tag "Twitter", nil, class: "col-sm-2 control-label" %>
    	<div class="col-sm-10">
			<%= form.text_field :twitter, class: "form-control", placeholder: "https://twitter.com/yourname"%>
		</div>
	</div> 
  	<div class="form-group">
    		<%= label_tag "github", nil, class: "col-sm-2 control-label" %>
    	<div class="col-sm-10">
			<%= form.text_field :github, class: "form-control", placeholder: "https://github.com/yourname" %>
		</div>
	</div> 
  	<div class="form-group">
    		<%= label_tag "Dribble", nil, class: "col-sm-2 control-label" %>
    	<div class="col-sm-10">
			<%= form.text_field :dribble, class: "form-control", placeholder: "https://dribbble.com/yourname"%>
		</div>
	</div> 
  	<div class="form-group">
    		<%= label_tag "Behance", nil, class: "col-sm-2 control-label" %>
    	<div class="col-sm-10">
			<%= form.text_field :behance, class: "form-control", placeholder: "https://www.behance.net/yourname"%>
		</div>
	</div> 

  	<div class="form-group">
    		<%= label_tag "Codepen", nil, class: "col-sm-2 control-label" %>
    	<div class="col-sm-10">
			<%= form.text_field :codepen, class: "form-control", placeholder: "http://codepen.io/yourname/"%>
		</div>
	</div> 

	<h2 class="skills-title">skills</h2>





	<div class="input-group-btn skill-group">
		<div class="btn-group" data-toggle="buttons">
			<%= hidden_field_tag "user[skill_ids][]", nil %>


			<% @skills.each do |skill| %>
			<% if skill.user_ids.include?current_user.id %>
				<% skill_class = "active" %>
			<% else %>
				<% skill_class = ""  %>
			<% end %>
			   <label class="btn btn-default skill-button <%= skill_class %>"><%= skill.skill_name %>
				<%= check_box_tag "user[skill_ids][]", skill.id, current_user.skill_ids.include?(skill.id), id: dom_id(skill) %>
              </label>

			<% end %>
		</div>
	</div>

	  	<div class="form-group">
 		<%= form.submit "Update Profile", class: "btn btn-default profile-submit" %>
  	</div>

<% end %>

app/views/profiles/index.html.erb
<div class="text-center skills-dropdown">
 <div class="btn-group">
	<div class="dropdown">
	  <button class="btn btn-default btn-lg dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown">
	    Skills
	    <span class="caret"></span>
	  </button>
	  <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">

		<% @skills.each do |s| %>	
	    	<li role="presentation"> <%= link_to s.skill_name, skill_path(:id => s.id), :method => :get  %> </li>
		<% end %>
	  </ul>
	</div>
  </div>
</div>

 <%= render "profile" %>

app/views/profiles/show.html.erb
<% user = @user %>
	<div class="profile-entry">

    <div class="profile-image-div">
			<%= image_tag user.profile.avatar.url(:medium), size: "125x125" %>
		</div>

    <div class="profile-text">
			<h3 class="title"><%=user.first_name + " " + user.last_name if user.first_name && user.last_name %></h3>
			<% if !user.profile.position.blank? && !user.profile.company.blank? %>
				<p><strong><%= user.profile.position + " @ " + user.profile.company  %></strong></p>
			<% end %>

				<p><a href="mailto:<%= user.email %>"><%= user.email %></a></p>
			<% if !user.profile.phone.blank? %>
				<% number = number_to_phone(user.profile.phone.tr('^0-9', '',).to_i, delimiter: ".") %>
				<p><a href="tel:<%= number %>"><%= number %></a></p>
			<% end %>

			<% if !user.profile.position.blank? %>
				<p>"<%= user.profile.micro_bio %>" </p>
			<% end %>
		</div>

		<div class="profile-socmed-div">
			<ul class="profile-ul" >
				<% if !user.profile.linked_in.blank? %>
				 	<li class="profile-socmed"><a href="<%= user.profile.linked_in %>" target="_blank"> <i class="fa fa-linkedin fontaweplus"></i></a> </li>
				<% end %>

				<% if !user.profile.twitter.blank? %>
					<li class="profile-socmed"><a href="<%= user.profile.twitter %>" target="_blank"> <i class="fa fa-twitter-square fontaweplus"></i></a> </li>
				<% end %>

				<% if !user.profile.github.blank? %>
					<li class="profile-socmed"><a href="<%= user.profile.github %>" target="_blank"> <i class="fa fa-github-square fontaweplus"></i></a> </li>
				<% end %>

				<% if !user.profile.dribble.blank? %>
					<li class="profile-socmed"><a href="<%= user.profile.dribble %>" target="_blank"> <i class="fa fa-dribbble fontaweplus"></i></a> </li>
				<% end %>

				<% if !user.profile.behance.blank? %>
					<li class="profile-socmed"><a href="<%= user.profile.behance %>" target="_blank"> <i class="fa fa-behance-square fontaweplus"></i></a> </li>
				<% end %>

				<% if !user.profile.codepen.blank? %>
					<li class="profile-socmed"><a href="<%= user.profile.codepen %>" target="_blank"> <i class="fa fa-codepen fontaweplus"></i></a> </li>
				<% end %>
			</ul>
		</div>

		<div class="profile-label-div">
			<ul class="profile-ul">
				<% user.skills.each do |skill| %>
					<li class="profile-label"><span class="label label-default2"><%= link_to skill.skill_name, skill_path(skill.id) %></span></li>
				<% end %>
			</ul>
		</div>

	</div>

  <% if @posts.present? %>
  <h2>Recent Activity</h2>

  <% @posts.each do |post| %>


  	<div class="post-container clearfix">

          <div class="post" >
    	        <div class = "initial-post">
    	          <h3 class="title writer"><%= post.user.first_name + " " + post.user.last_name %> <span class ="deleted">


    	          </span></h3>



    	           <%= simple_format(post.post_content, class: 'content') %>
    	          <p class="posted">posted <%= distance_of_time_in_words_to_now(post.created_at) + " ago." %>
    	          </p>


    	        </div>
    			  <% if post.comments.present? %>
      				 <div class="comments-wrapper clearfix">

      			        <div class="comments">
      			          <% @comments.each do |comment| %>
      			              <% if comment.post_id == post.id %>
      			        	      <div class="comment">

      			                <h3 class="writer title"><%= link_to_unless_current comment.user.first_name + " " + comment.user.last_name, profile_path(comment.user.id)  %>


      			                 </h3>
      			        	       <%= simple_format(comment.comment_content, class: 'content') %>
      			        	       <p class="posted-comment">posted <%= distance_of_time_in_words_to_now(comment.created_at) + " ago." %></p>
      			                </div>
      			              <% end %>
      			          <% end %>
      			        </div>
      		        </div>
    		    <% end %>
    	    </div>
        </div>
      <% end %>

<% end %>