config/routes.rb
# == Route Map
#
#                   Prefix Verb   URI Pattern                          Controller#Action
#         new_user_session GET    /users/sign_in(.:format)             devise/sessions#new
#             user_session POST   /users/sign_in(.:format)             devise/sessions#create
#     destroy_user_session DELETE /users/sign_out(.:format)            devise/sessions#destroy
#            user_password POST   /users/password(.:format)            devise/passwords#create
#        new_user_password GET    /users/password/new(.:format)        devise/passwords#new
#       edit_user_password GET    /users/password/edit(.:format)       devise/passwords#edit
#                          PATCH  /users/password(.:format)            devise/passwords#update
#                          PUT    /users/password(.:format)            devise/passwords#update
# cancel_user_registration GET    /users/cancel(.:format)              registrations#cancel
#        user_registration POST   /users(.:format)                     registrations#create
#    new_user_registration GET    /users/sign_up(.:format)             registrations#new
#   edit_user_registration GET    /users/edit(.:format)                registrations#edit
#                          PATCH  /users(.:format)                     registrations#update
#                          PUT    /users(.:format)                     registrations#update
#                          DELETE /users(.:format)                     registrations#destroy
#   accept_user_invitation GET    /users/invitation/accept(.:format)   invitations#edit
#   remove_user_invitation GET    /users/invitation/remove(.:format)   invitations#destroy
#          user_invitation POST   /users/invitation(.:format)          invitations#create
#      new_user_invitation GET    /users/invitation/new(.:format)      invitations#new
#                          PATCH  /users/invitation(.:format)          invitations#update
#                          PUT    /users/invitation(.:format)          invitations#update
#                directory GET    /directory(.:format)                 profiles#index
#              admin_index GET    /admin/index(.:format)               admin#index
#             admin_update PATCH  /admin/update(.:format)              admin#update
#            admin_destroy DELETE /admin/destroy(.:format)             admin#destroy
#          schedules_index GET    /schedules/index(.:format)           schedules#index
#           schedules_test GET    /schedules/test(.:format)            schedules#test
#     create_slots_mentors POST   /mentors/create_slots(.:format)      mentors#create_slots
#     destroy_slots_mentor DELETE /mentors/:id/destroy_slots(.:format) mentors#destroy_slots
#      update_slots_mentor PATCH  /mentors/:id/update_slots(.:format)  mentors#update_slots
#     release_slots_mentor PATCH  /mentors/:id/release_slots(.:format) mentors#release_slots
#                  mentors GET    /mentors(.:format)                   mentors#index
#                          POST   /mentors(.:format)                   mentors#create
#               new_mentor GET    /mentors/new(.:format)               mentors#new
#              edit_mentor GET    /mentors/:id/edit(.:format)          mentors#edit
#                   mentor GET    /mentors/:id(.:format)               mentors#show
#                          PATCH  /mentors/:id(.:format)               mentors#update
#                          PUT    /mentors/:id(.:format)               mentors#update
#                          DELETE /mentors/:id(.:format)               mentors#destroy
#             hiring_posts GET    /posts/hiring(.:format)              posts#hiring
#            promote_posts GET    /posts/promote(.:format)             posts#promote
#             launch_posts GET    /posts/launch(.:format)              posts#launch
#              tools_posts GET    /posts/tools(.:format)               posts#tools
#      request_thing_posts GET    /posts/request_thing(.:format)       posts#request_thing
#              event_posts GET    /posts/event(.:format)               posts#event
#                    posts GET    /posts(.:format)                     posts#index
#                          POST   /posts(.:format)                     posts#create
#                 new_post GET    /posts/new(.:format)                 posts#new
#                edit_post GET    /posts/:id/edit(.:format)            posts#edit
#                     post GET    /posts/:id(.:format)                 posts#show
#                          PATCH  /posts/:id(.:format)                 posts#update
#                          PUT    /posts/:id(.:format)                 posts#update
#                          DELETE /posts/:id(.:format)                 posts#destroy
#              sort_skills POST   /skills/sort(.:format)               skills#sort
#                   skills GET    /skills(.:format)                    skills#index
#                          POST   /skills(.:format)                    skills#create
#                new_skill GET    /skills/new(.:format)                skills#new
#               edit_skill GET    /skills/:id/edit(.:format)           skills#edit
#                    skill GET    /skills/:id(.:format)                skills#show
#                          PATCH  /skills/:id(.:format)                skills#update
#                          PUT    /skills/:id(.:format)                skills#update
#                          DELETE /skills/:id(.:format)                skills#destroy
#                 profiles GET    /profiles(.:format)                  profiles#index
#                          POST   /profiles(.:format)                  profiles#create
#              new_profile GET    /profiles/new(.:format)              profiles#new
#             edit_profile GET    /profiles/:id/edit(.:format)         profiles#edit
#                  profile GET    /profiles/:id(.:format)              profiles#show
#                          PATCH  /profiles/:id(.:format)              profiles#update
#                          PUT    /profiles/:id(.:format)              profiles#update
#                          DELETE /profiles/:id(.:format)              profiles#destroy
#                 comments GET    /comments(.:format)                  comments#index
#                          POST   /comments(.:format)                  comments#create
#              new_comment GET    /comments/new(.:format)              comments#new
#             edit_comment GET    /comments/:id/edit(.:format)         comments#edit
#                  comment GET    /comments/:id(.:format)              comments#show
#                          PATCH  /comments/:id(.:format)              comments#update
#                          PUT    /comments/:id(.:format)              comments#update
#                          DELETE /comments/:id(.:format)              comments#destroy
#                     root GET    /                                    posts#index
#


Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations', invitations: 'invitations' }

  get 'directory/', to: 'profiles#index'

  get 'admin/index'

  patch 'admin/update'

  delete 'admin/destroy'

  get 'schedules/index'

  get 'schedules/test'

  resources :mentors do
    collection do
      post :create_slots
    end
    member do
      delete :destroy_slots
      patch :update_slots
      patch :release_slots
    end
  end


  resources :posts do
    collection do
      get :hiring
      get :promote
      get :launch
      get :tools
      get :request_thing
      get :event
    end
  end

  resources :skills do
    collection { post :sort }
  end

  resources :profiles
  resources :comments


  root "posts#index"

end

app/controllers/mentors_controller.rb
class MentorsController < ApplicationController



  def index
  	@sheets = Sheet.where(user_id: current_user).order("sheets.date ASC")
  	@sheet = Sheet.new
    authorize! :create, @sheet

  end

  def create
  	@newsheet = current_user.sheets.build(sheet_params)
        authorize! :create, @newsheet

      	if @newsheet.save(sheet_params)
          redirect_to :back


        else
          flash[:alert] = "Sheet was not created successfully."
          redirect_to :back
        end


<<<<<<< HEAD
  end
=======

>>>>>>> 063e5da19450a75e5dbb714d4d0eb55fd3d34fb8



  def destroy
    sheet = Sheet.find(params[:id])
    authorize! :destroy, sheet
  	if
      sheet.destroy
      redirect_to :back
    else
      flash[:notice] = "The sheet could not be deleted."
      redirect_to :back
    end
  end

  def create_slots
    authorize! :create, Slot

  	@newslot = Slot.create(slot_params)

      	if @newslot.save(slot_params)
          redirect_to :back

        else
          flash[:alert] = "The slot was not created successfully. Please verify that all fields were filled in."
          redirect_to :back
        end
  end

  def destroy_slots
    if
      slot = Slot.find(params[:id]).destroy
      redirect_to :back
     	authorize! :destroy, Slot
    else
      flash[:notice] = "The slot could not be deleted."
      redirect_to :back
    end
  end

  def update_slots
    if
      slot = Slot.find(params[:id])
      authorize! :update, slot
      slot.update_attributes(:user_id => current_user.id)
      redirect_to :back
    else
      flash[:notice] = "The slot could not be updated."
      redirect_to :back
    end
  end

<<<<<<< HEAD
  # def release_slots
  #   if slot = Slot.find(params[:id]).
  #     authorize! :update, slot
  #     slot.update_attributes(:user_id => nil)
  #     redirect_to :back
  #   else
  #     flash[:notice] = "The slot could not be released."
  #     redirect_to :back
  #   end
  # end
=======
  def release_slots
    if
      slot = Slot.find(params[:id]).
      authorize! :update, slot
      slot.update_attributes(:user_id => nil)
      redirect_to :back
    else
      flash[:notice] = "The slot could not be released."
      redirect_to :back
    end
  end
>>>>>>> 063e5da19450a75e5dbb714d4d0eb55fd3d34fb8


  private

    def sheet_params
      params.require(:sheet).permit(:user_id, :date, :description)
    end
    def slot_params
      params.require(:slot).permit(:sheet_id, :start_time, :end_time)
    end
    def mentee_params
      params.require(:slot).permit(:user_id)
    end

end

app/helpers/mentor_helper.rb
module MentorHelper
end

app/views/mentors/create.html.erb
<h1>Mentor#create</h1>
<p>Find me in app/views/mentor/create.html.erb</p>

app/views/mentors/destroy.html.erb
<h1>Mentor#destroy</h1>
<p>Find me in app/views/mentor/destroy.html.erb</p>

app/views/mentors/index.html.erb
<h1>Mentor</h1>
<% picker_iterator1 = 1 %>
<% picker_iterator2 = 10000 %>


<p class="mentor-title">Create an Appointment Sheet</p>
	<div class="input-append">
		<div class="input-group">
			<%= form_for :sheet,  method: :post do |f| %>
  				<span class="mentor-description">Description: </span> <%= f.text_field :description, placeholder: "Technical advice, etc." %>
	 			<span class="mentor-description">Date: </span> <%= f.text_field :date, placeholder: Time.now.strftime("%m/%d/%Y"), :data => {:provide => "datepicker"} %>
                <%= f.submit "Create new sheet", class: "btn btn-default time-slot-submit" %>
			<% end %>
	 	</div>
	</div>

<br>

<% if @sheets.present? %>
	<p class="mentor-title">Add Sign-up Time Slots</p>
        <% @sheets.each do |s| %>
    		<p>
                <span class="mentor-current-sheet">Sheet: </span> 
                <span class="mentor-current-description"> <%= s.description %></span>
                <span> on </span>   
                <span class="mentor-current-description"><%= s.date %></span> <span> <%= link_to 'x', { :controller => 'mentors', :action => 'destroy', :id => s.id }, data: { confirm: "Click 'confirm' to delete this sheet." }, :method => :delete, class: "delete-content" %> </span>
            </p>
            <% sorted_slots = s.slots.sort_by { |obj| obj.start_time } %>
    		<% sorted_slots.each do |sl| %>
    			<span class="mentor-current-time"> <%= sl.start_time + " - " + sl.end_time  %> </span>
                <span class="mentor-pipe">  | </span>
    			<% if sl.user_id %>
    				<span class="mentor-mentee-name"> <%= link_to sl.user.first_name + " " + sl.user.last_name, profile_path(sl.user.id) %> </span>
                    <%= " is signed up for this time slot."%>
                      <span class="delete-content"> <%= link_to 'x', { :controller => 'mentors', :action => 'destroy_slots', :id => sl.id }, data: { confirm: "Click 'confirm' to delete this slot. #{sl.user.first_name} #{sl.user.last_name} will be alerted that you have cancelled this slot." }, :method => :delete, class: "delete-content" %> </span>
    			<% else %>
    				<span class="mentor-slot-available"> Available </span>
                    <span class="delete-content"> <%= link_to 'x', { :controller => 'mentors', :action => 'destroy_slots', :id => sl.id }, data: { confirm: "Click 'confirm' to delete this slot." }, :method => :delete, class: "delete-content" %> </span>
    			<% end %>
              

    			<br>

    		<% end %>
                <%= form_for :slot, url: create_slots_mentors_path, method: :post do |f| %>
                    <%= f.hidden_field :sheet_id, :value => s.id %>

            <div class="container">
                <div class="row">
                    <div class='col-sm-4'>
                        <div class="form-group">
                            <div class='input-group date' id='datetimepicker<%= picker_iterator1 %>'>
                                <span class="input-group-addon">Start Time</span>
                                <%= f.text_field :start_time,  class: "form-control" %>
                                <span class="input-group-addon">
                                    <span class="glyphicon glyphicon-time"></span>
                                </span>
                            </div>
                            
                            <div class='input-group date' id='datetimepicker<%= picker_iterator2 %>'>
                                <span class="input-group-addon end-time">End Time  </span>
                                <%= f.text_field :end_time,  class: "form-control" %>
                                <span class="input-group-addon">
                                    <span class="glyphicon glyphicon-time"></span>
                                </span>
                            </div>
                            <div class='input-group'>
                                <%= f.submit "New Time Slot", class: "btn btn-default time-slot-submit" %>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
<script type="text/javascript">
    $(function () {
        $('#datetimepicker<%= picker_iterator1 %>').datetimepicker({
            pickDate: false,
            minuteStepping:5
        });
    });
    $(function () {
        $('#datetimepicker<%= picker_iterator2 %>').datetimepicker({
            pickDate: false,
            minuteStepping:5
        });
    });

</script>
<% picker_iterator1 += 1 %>
<% picker_iterator2 += 1 %>

        <% end %>

    <% end %>

<% end %>

app/views/mentors/update.html.erb
<h1>Mentor#update</h1>
<p>Find me in app/views/mentor/update.html.erb</p>