config/routes.rb
# == Route Map
#
#                   Prefix Verb   URI Pattern                          Controller#Action
#         new_user_session GET    /users/sign_in(.:format)             devise/sessions#new
#             user_session POST   /users/sign_in(.:format)             devise/sessions#create
#     destroy_user_session DELETE /users/sign_out(.:format)            devise/sessions#destroy
#            user_password POST   /users/password(.:format)            devise/passwords#create
#        new_user_password GET    /users/password/new(.:format)        devise/passwords#new
#       edit_user_password GET    /users/password/edit(.:format)       devise/passwords#edit
#                          PATCH  /users/password(.:format)            devise/passwords#update
#                          PUT    /users/password(.:format)            devise/passwords#update
# cancel_user_registration GET    /users/cancel(.:format)              registrations#cancel
#        user_registration POST   /users(.:format)                     registrations#create
#    new_user_registration GET    /users/sign_up(.:format)             registrations#new
#   edit_user_registration GET    /users/edit(.:format)                registrations#edit
#                          PATCH  /users(.:format)                     registrations#update
#                          PUT    /users(.:format)                     registrations#update
#                          DELETE /users(.:format)                     registrations#destroy
#   accept_user_invitation GET    /users/invitation/accept(.:format)   invitations#edit
#   remove_user_invitation GET    /users/invitation/remove(.:format)   invitations#destroy
#          user_invitation POST   /users/invitation(.:format)          invitations#create
#      new_user_invitation GET    /users/invitation/new(.:format)      invitations#new
#                          PATCH  /users/invitation(.:format)          invitations#update
#                          PUT    /users/invitation(.:format)          invitations#update
#                directory GET    /directory(.:format)                 profiles#index
#              admin_index GET    /admin/index(.:format)               admin#index
#             admin_update PATCH  /admin/update(.:format)              admin#update
#            admin_destroy DELETE /admin/destroy(.:format)             admin#destroy
#          schedules_index GET    /schedules/index(.:format)           schedules#index
#           schedules_test GET    /schedules/test(.:format)            schedules#test
#     create_slots_mentors POST   /mentors/create_slots(.:format)      mentors#create_slots
#     destroy_slots_mentor DELETE /mentors/:id/destroy_slots(.:format) mentors#destroy_slots
#      update_slots_mentor PATCH  /mentors/:id/update_slots(.:format)  mentors#update_slots
#     release_slots_mentor PATCH  /mentors/:id/release_slots(.:format) mentors#release_slots
#                  mentors GET    /mentors(.:format)                   mentors#index
#                          POST   /mentors(.:format)                   mentors#create
#               new_mentor GET    /mentors/new(.:format)               mentors#new
#              edit_mentor GET    /mentors/:id/edit(.:format)          mentors#edit
#                   mentor GET    /mentors/:id(.:format)               mentors#show
#                          PATCH  /mentors/:id(.:format)               mentors#update
#                          PUT    /mentors/:id(.:format)               mentors#update
#                          DELETE /mentors/:id(.:format)               mentors#destroy
#             hiring_posts GET    /posts/hiring(.:format)              posts#hiring
#            promote_posts GET    /posts/promote(.:format)             posts#promote
#             launch_posts GET    /posts/launch(.:format)              posts#launch
#              tools_posts GET    /posts/tools(.:format)               posts#tools
#      request_thing_posts GET    /posts/request_thing(.:format)       posts#request_thing
#              event_posts GET    /posts/event(.:format)               posts#event
#                    posts GET    /posts(.:format)                     posts#index
#                          POST   /posts(.:format)                     posts#create
#                 new_post GET    /posts/new(.:format)                 posts#new
#                edit_post GET    /posts/:id/edit(.:format)            posts#edit
#                     post GET    /posts/:id(.:format)                 posts#show
#                          PATCH  /posts/:id(.:format)                 posts#update
#                          PUT    /posts/:id(.:format)                 posts#update
#                          DELETE /posts/:id(.:format)                 posts#destroy
#              sort_skills POST   /skills/sort(.:format)               skills#sort
#                   skills GET    /skills(.:format)                    skills#index
#                          POST   /skills(.:format)                    skills#create
#                new_skill GET    /skills/new(.:format)                skills#new
#               edit_skill GET    /skills/:id/edit(.:format)           skills#edit
#                    skill GET    /skills/:id(.:format)                skills#show
#                          PATCH  /skills/:id(.:format)                skills#update
#                          PUT    /skills/:id(.:format)                skills#update
#                          DELETE /skills/:id(.:format)                skills#destroy
#                 profiles GET    /profiles(.:format)                  profiles#index
#                          POST   /profiles(.:format)                  profiles#create
#              new_profile GET    /profiles/new(.:format)              profiles#new
#             edit_profile GET    /profiles/:id/edit(.:format)         profiles#edit
#                  profile GET    /profiles/:id(.:format)              profiles#show
#                          PATCH  /profiles/:id(.:format)              profiles#update
#                          PUT    /profiles/:id(.:format)              profiles#update
#                          DELETE /profiles/:id(.:format)              profiles#destroy
#                 comments GET    /comments(.:format)                  comments#index
#                          POST   /comments(.:format)                  comments#create
#              new_comment GET    /comments/new(.:format)              comments#new
#             edit_comment GET    /comments/:id/edit(.:format)         comments#edit
#                  comment GET    /comments/:id(.:format)              comments#show
#                          PATCH  /comments/:id(.:format)              comments#update
#                          PUT    /comments/:id(.:format)              comments#update
#                          DELETE /comments/:id(.:format)              comments#destroy
#                     root GET    /                                    posts#index
#


Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations', invitations: 'invitations' }

  get 'directory/', to: 'profiles#index'

  get 'admin/index'

  patch 'admin/update'

  delete 'admin/destroy'

  get 'schedules/index'

  get 'schedules/test'

  resources :mentors do
    collection do
      post :create_slots
    end
    member do
      delete :destroy_slots
      patch :update_slots
      patch :release_slots
    end
  end


  resources :posts do
    collection do
      get :hiring
      get :promote
      get :launch
      get :tools
      get :request_thing
      get :event
    end
  end

  resources :skills do
    collection { post :sort }
  end

  resources :profiles
  resources :comments


  root "posts#index"

end

app/models/post.rb
class Post < ActiveRecord::Base
  
  has_many :comments
  belongs_to :user

  acts_as_mentioner
 
  validates_presence_of :post_content
  validates_presence_of :user_id




  default_scope -> { order('created_at DESC') }
end

# ## Schema Information
#
# Table name: `posts`
#
# ### Columns
#
# Name                | Type               | Attributes
# ------------------- | ------------------ | ---------------------------
# **`id`**            | `integer`          | `not null, primary key`
# **`user_id`**       | `integer`          |
# **`post_content`**  | `text`             |
# **`created_at`**    | `datetime`         |
# **`updated_at`**    | `datetime`         |
# **`hiring`**        | `boolean`          | `default(FALSE)`
# **`promote`**       | `boolean`          | `default(FALSE)`
# **`launch`**        | `boolean`          | `default(FALSE)`
# **`tools`**         | `boolean`          | `default(FALSE)`
# **`request`**       | `boolean`          | `default(FALSE)`
# **`event`**         | `boolean`          | `default(FALSE)`
#
# ### Indexes
#
# * `index_posts_on_user_id`:
#     * **`user_id`**
#

app/controllers/posts_controller.rb
class PostsController < ApplicationController
before_action :authenticate_user!
load_and_authorize_resource

  def index
    @comments = Comment.order("comments.created_at ASC")  

    @page = "Whiteboard"
    @posts = Post.order("posts.created_at DESC").page(params[:page]).per_page(10)
    user_name = User.pluck(:first_name, :last_name)
    a = []
    user_name.each do |i|
      a << i.join("_")
    end
    @username = a

  end

  def new
    @newpost = current_user.posts.build({:name => "default"})

  end

  def create

#creates an array with a list of users, @user_name
      u = User.all
      h = {}
      u.each do |i|
        h["@" + i.first_name + "_" + i.last_name] = i.id
      end

      @newpost = current_user.posts.new(post_params)

#adds <a>for http and https
      arr = @newpost.post_content.split(" ")
      arr2 = []
      arr.each do |word|
        if word.include? "http://" 
          a_tag = "<span class='link'><a href= '#{word}' >#{word}</a></span>"
          word = a_tag
        elsif word.include? "https://"
          a_tag = "<span class='link'><a href= '#{word}' >#{word}</a></span>"
          word = a_tag
        end
        arr2 << word
      end
      string = arr2.join(" ")
      @newpost.post_content = string


      unless @newpost.post_content == ""
      	if @newpost.save
          h.each do |k,v|
            if @newpost.post_content.include? k
              @newpost.mention!(User.find_by_id(v))
              MentionNotification.mention_post(v, @newpost).deliver 
            end
            if (@newpost.post_content.include? "@everyone")
              if @newpost.user.role == "admin"
                MentionNotification.mention_all_post(@newpost, @newpost.user).deliver
              else
                flash[:notice] = "FYI, @everyone email notifications are generated only by Administator posts."
              end

            end
          end
          redirect_to root_path

  
        else
          flash[:alert] = "Post was not created successfully."
          @posts = Post.order("posts.created_at DESC")
          @comments = Comment.order("comments.created_at ASC")
          redirect_to root_path
        end
      else
          flash[:alert] = "Post cannot be blank."
          @posts = Post.order("posts.created_at DESC")
          @comments = Comment.order("comments.created_at ASC")
          redirect_to root_path        

      end

  end

  def delete
  end

  def destroy
    if current_user == Post.find(params[:id]).user
      post = Post.find(params[:id]).destroy
      redirect_to :back
    else
      flash[:notice] = "You are not authorized to delete that post."
      redirect_to :back
    end

  end

  def hiring
    @posts = Post.where({ hiring: 1}).order("posts.created_at DESC").page(params[:page]).per_page(10)
    @comments = Comment.order("comments.created_at ASC")
    @page = "Hiring"
    user_name = User.pluck(:first_name, :last_name)
    a = []
    user_name.each do |i|
      a << i.join("_")
    end
    @username = a
  end

  def promote
    @posts = Post.where({ promote: 1}).order("posts.created_at DESC").page(params[:page]).per_page(10)
    @comments = Comment.order("comments.created_at ASC")
    @page = "Promote"
    user_name = User.pluck(:first_name, :last_name)
    a = []
    user_name.each do |i|
      a << i.join("_")
    end
    @username = a
  end

  def launch
    @posts = Post.where({ launch: 1}).order("posts.created_at DESC").page(params[:page]).per_page(10)
    @comments = Comment.order("comments.created_at ASC")
    @page = "Launch"
    user_name = User.pluck(:first_name, :last_name)
    a = []
    user_name.each do |i|
      a << i.join("_")
    end
    @username = a
  end

  def tools
    @posts = Post.where({ tools: 1}).order("posts.created_at DESC").page(params[:page]).per_page(10)
    @comments = Comment.order("comments.created_at ASC")
    @page = "Tools"
    user_name = User.pluck(:first_name, :last_name)
    a = []
    user_name.each do |i|
      a << i.join("_")
    end
    @username = a
  end
  
  def request_thing
    @posts = Post.where({ request: 1}).order("posts.created_at DESC").page(params[:page]).per_page(10)
    @comments = Comment.order("comments.created_at ASC")
    @page = "Requests"
    user_name = User.pluck(:first_name, :last_name)
    a = []
    user_name.each do |i|
      a << i.join("_")
    end
    @username = a
  end
  
  def event
    @posts = Post.where({ event: 1}).order("posts.created_at DESC").page(params[:page]).per_page(10)
    @comments = Comment.order("comments.created_at ASC")
    @page = "Events"
    user_name = User.pluck(:first_name, :last_name)
    a = []
    user_name.each do |i|
      a << i.join("_")
    end
    @username = a
  end




private

    def post_params
      params.require(:post).permit(:user_id, :post_content, :hiring, :promote, :launch, :tools, :request, :event)
    end


end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_delete_modal.html.erb
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">Modal title</h4>
      </div>
      <div class="modal-body">
        

      <%= form_for(:post, :url => {:action => 'destroy', :id => post.id}) do |f| %>

    <p>Are you sure you want to permanently delete this post?</p>

              </div>
      <div class="modal-footer">





    <div class="form-buttons">
      <%= submit_tag("Delete", :id=>"button", :class=>"btn btn-default", :name=>"submit") %>
    </div>

    <% end %>
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        
      
      </div>
    </div>
  </div>
</div>

app/views/posts/_index.html.erb
   <div class="text-center">
     <div class="btn-group">

        <button class="btn btn-default btn-lg dropdown-toggle " type="button" data-toggle="dropdown">
          <%= @page %> <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" role="menu">
          <li><%= link_to_unless_current("Whiteboard", root_path) do 
                  content_tag(:a, "Whiteboard", class: "disabled2")
                  end%> 
          </li> 
          <li><%= link_to_unless_current("Hiring", hiring_posts_path) do 
                  content_tag(:a, "Hiring", class: "disabled2")
                  end%> 
          </li> 
          <li><%= link_to_unless_current("Promote", promote_posts_path) do 
                  content_tag(:a, "Promote", class: "disabled2")
                  end%> 
          </li> 
          <li><%= link_to_unless_current("Launch", launch_posts_path) do 
                  content_tag(:a, "Launch", class: "disabled2")
                  end%> 
          </li> 
          <li><%= link_to_unless_current("Tools", tools_posts_path) do 
                  content_tag(:a, "Tools", class: "disabled2")
                  end%> 
          </li> 
          <li><%= link_to_unless_current("Request", request_thing_posts_path) do 
                  content_tag(:a, "Hiring", class: "disabled2")
                  end%> 
          </li> 
          <li><%= link_to_unless_current("Event", event_posts_path) do 
                  content_tag(:a, "Event", class: "disabled2")
                  end%> 
          </li> 
      </ul>
  </div>
</div>

   <h3 id="newpost" class="new-post"> &lt;new_post&gt;</h3>
     


      <div class=" new-post-div" id="hiddenTextareaDiv">
        <div class="input-group-btn">



          <%= form_for(:post, :url => {:action => 'create'}) do |f| %>
           
            <div class="btn-group" data-toggle="buttons">
              <label class="btn active">
                <%= f.radio_button(:general, true) %>Whiteboard 
              </label>

              <label class="btn">
                <%= f.check_box(:hiring) %>Hiring 
              </label>
              <label class="btn">
                <%= f.check_box(:promote) %>Promote 
              </label>
              <label class="btn">
                <%= f.check_box(:launch) %>Launch 
              </label>
              <label class="btn">
                <%= f.check_box(:tools) %>Tools 
              </label>
              <label class="btn">
                <%= f.check_box(:request) %>Request 
              </label>
              <label class="btn">
                <%= f.check_box(:event) %>Event
              </label>
            </div>
          <%= f.text_area(:post_content, rows:5, class: "form-control newPostTextArea form-validate") %>  
            <script> 
                $(function(){
                    data = <%= raw @username.compact.to_json %> ;
                    $('textarea').atwho({at:"@", 'data':data});
                });
            </script>
         


          <%= f.submit(class: 'btn btn-default') %>
        </div>
        <% end %>
     </div>     

<div id="posts">
  <%= render "post" %>
</div>
    <%= will_paginate @posts %>

<br>
<br>
<br>

app/views/posts/_post.html.erb
<% @posts.each do |post| %>
      

  <div class="post-container">
    <div class="post clearfix " >
      <div class = "initial-post ">
        <h3 class="title writer"> <%= link_to post.user.first_name + " " + post.user.last_name, profile_path(post.user.id)  %> <span class ="deleted">
        <% if user_signed_in? %>
          <%= link_to "x", post, method: :delete, data: { confirm: "Click 'Confirm' to delete." } if can? :destroy, post %>
        <% end %>

        </span></h3>
        


        <%= simple_format(post.post_content, class: 'content') %>
        <p class="posted">posted <%= distance_of_time_in_words_to_now(post.created_at) + " ago." %>
        </p>

      </div>
    </div>
  <% if post.comments.present? %>
    <div class="comments-wrapper clearfix">
      <div class="comments">
        <% @comments.each do |comment| %>
            <% if comment.post_id == post.id %>
      	      <div class="comment">

              <h3 class="writer title"><%= link_to comment.user.first_name + " " + comment.user.last_name, profile_path(comment.user.id)  %>
                <% if user_signed_in? %>
                    <span class ="comment-deleted">
                      <%= link_to "x", comment, method: :delete, data: { confirm: "Click 'Confirm' to delete." } if can? :destroy, comment %>
                    </span>
                <% end %>

               </h3>
      	       <%= simple_format(comment.comment_content, class: 'content') %>
      	       <p class="posted-comment">posted <%= distance_of_time_in_words_to_now(comment.created_at) + " ago." %></p>
              </div>
            <% end %>          
        <% end %>
      </div>
    </div>
  <% end %>

  <% if post.comments.present? %>
    <% background_class = "reply-background-class1" %>
  <% else %>
    <% background_class = "reply-background-class2" %>
  <% end %>

    <div class="reply-form clearfix <%= background_class %>"> 
        <%= form_for(:comment, :url => {:controller => :comments, :action => 'create'}) do |f| %>
        <%= f.hidden_field :post_id, :value => post.id %>
          <%= f.text_area(:comment_content, :placeholder => "Your comment...",  rows:2, class: "reply-txtarea  form-validate") %>  
        <%= f.submit "<reply>", class: 'reply-submit' %>

        <% end %>     
    </div> 

  </div>

<% end %>

app/views/posts/delete.html.erb
<h1>Post#delete</h1>
<p>Find me in app/views/post/delete.html.erb</p>

app/views/posts/event.html.erb
 <%= render "index"%>

app/views/posts/hiring.html.erb
 <%= render "index"%>

app/views/posts/index.html.erb
 <%= render "index" %>

app/views/posts/index.js.erb
$('#posts').append('<%= j render("post") %>');
<% if @posts.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate(@posts) %>');
<% else %>
  $('.pagination').remove();
  sleep(1);
  $(".reply-form").hide();

<% end %>

app/views/posts/launch.html.erb
 <%= render "index"%>

app/views/posts/promote.html.erb
 <%= render "index"%>

app/views/posts/request_thing.html.erb
 <%= render "index"%>

app/views/posts/tools.html.erb
 <%= render "index"%>
 