config/routes.rb
# == Route Map
#
#                   Prefix Verb   URI Pattern                          Controller#Action
#         new_user_session GET    /users/sign_in(.:format)             devise/sessions#new
#             user_session POST   /users/sign_in(.:format)             devise/sessions#create
#     destroy_user_session DELETE /users/sign_out(.:format)            devise/sessions#destroy
#            user_password POST   /users/password(.:format)            devise/passwords#create
#        new_user_password GET    /users/password/new(.:format)        devise/passwords#new
#       edit_user_password GET    /users/password/edit(.:format)       devise/passwords#edit
#                          PATCH  /users/password(.:format)            devise/passwords#update
#                          PUT    /users/password(.:format)            devise/passwords#update
# cancel_user_registration GET    /users/cancel(.:format)              registrations#cancel
#        user_registration POST   /users(.:format)                     registrations#create
#    new_user_registration GET    /users/sign_up(.:format)             registrations#new
#   edit_user_registration GET    /users/edit(.:format)                registrations#edit
#                          PATCH  /users(.:format)                     registrations#update
#                          PUT    /users(.:format)                     registrations#update
#                          DELETE /users(.:format)                     registrations#destroy
#   accept_user_invitation GET    /users/invitation/accept(.:format)   invitations#edit
#   remove_user_invitation GET    /users/invitation/remove(.:format)   invitations#destroy
#          user_invitation POST   /users/invitation(.:format)          invitations#create
#      new_user_invitation GET    /users/invitation/new(.:format)      invitations#new
#                          PATCH  /users/invitation(.:format)          invitations#update
#                          PUT    /users/invitation(.:format)          invitations#update
#                directory GET    /directory(.:format)                 profiles#index
#              admin_index GET    /admin/index(.:format)               admin#index
#             admin_update PATCH  /admin/update(.:format)              admin#update
#            admin_destroy DELETE /admin/destroy(.:format)             admin#destroy
#          schedules_index GET    /schedules/index(.:format)           schedules#index
#           schedules_test GET    /schedules/test(.:format)            schedules#test
#     create_slots_mentors POST   /mentors/create_slots(.:format)      mentors#create_slots
#     destroy_slots_mentor DELETE /mentors/:id/destroy_slots(.:format) mentors#destroy_slots
#      update_slots_mentor PATCH  /mentors/:id/update_slots(.:format)  mentors#update_slots
#     release_slots_mentor PATCH  /mentors/:id/release_slots(.:format) mentors#release_slots
#                  mentors GET    /mentors(.:format)                   mentors#index
#                          POST   /mentors(.:format)                   mentors#create
#               new_mentor GET    /mentors/new(.:format)               mentors#new
#              edit_mentor GET    /mentors/:id/edit(.:format)          mentors#edit
#                   mentor GET    /mentors/:id(.:format)               mentors#show
#                          PATCH  /mentors/:id(.:format)               mentors#update
#                          PUT    /mentors/:id(.:format)               mentors#update
#                          DELETE /mentors/:id(.:format)               mentors#destroy
#             hiring_posts GET    /posts/hiring(.:format)              posts#hiring
#            promote_posts GET    /posts/promote(.:format)             posts#promote
#             launch_posts GET    /posts/launch(.:format)              posts#launch
#              tools_posts GET    /posts/tools(.:format)               posts#tools
#      request_thing_posts GET    /posts/request_thing(.:format)       posts#request_thing
#              event_posts GET    /posts/event(.:format)               posts#event
#                    posts GET    /posts(.:format)                     posts#index
#                          POST   /posts(.:format)                     posts#create
#                 new_post GET    /posts/new(.:format)                 posts#new
#                edit_post GET    /posts/:id/edit(.:format)            posts#edit
#                     post GET    /posts/:id(.:format)                 posts#show
#                          PATCH  /posts/:id(.:format)                 posts#update
#                          PUT    /posts/:id(.:format)                 posts#update
#                          DELETE /posts/:id(.:format)                 posts#destroy
#              sort_skills POST   /skills/sort(.:format)               skills#sort
#                   skills GET    /skills(.:format)                    skills#index
#                          POST   /skills(.:format)                    skills#create
#                new_skill GET    /skills/new(.:format)                skills#new
#               edit_skill GET    /skills/:id/edit(.:format)           skills#edit
#                    skill GET    /skills/:id(.:format)                skills#show
#                          PATCH  /skills/:id(.:format)                skills#update
#                          PUT    /skills/:id(.:format)                skills#update
#                          DELETE /skills/:id(.:format)                skills#destroy
#                 profiles GET    /profiles(.:format)                  profiles#index
#                          POST   /profiles(.:format)                  profiles#create
#              new_profile GET    /profiles/new(.:format)              profiles#new
#             edit_profile GET    /profiles/:id/edit(.:format)         profiles#edit
#                  profile GET    /profiles/:id(.:format)              profiles#show
#                          PATCH  /profiles/:id(.:format)              profiles#update
#                          PUT    /profiles/:id(.:format)              profiles#update
#                          DELETE /profiles/:id(.:format)              profiles#destroy
#                 comments GET    /comments(.:format)                  comments#index
#                          POST   /comments(.:format)                  comments#create
#              new_comment GET    /comments/new(.:format)              comments#new
#             edit_comment GET    /comments/:id/edit(.:format)         comments#edit
#                  comment GET    /comments/:id(.:format)              comments#show
#                          PATCH  /comments/:id(.:format)              comments#update
#                          PUT    /comments/:id(.:format)              comments#update
#                          DELETE /comments/:id(.:format)              comments#destroy
#                     root GET    /                                    posts#index
#


Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations', invitations: 'invitations' }

  get 'directory/', to: 'profiles#index'

  get 'admin/index'

  patch 'admin/update'

  delete 'admin/destroy'

  get 'schedules/index'

  get 'schedules/test'

  resources :mentors do
    collection do
      post :create_slots
    end
    member do
      delete :destroy_slots
      patch :update_slots
      patch :release_slots
    end
  end


  resources :posts do
    collection do
      get :hiring
      get :promote
      get :launch
      get :tools
      get :request_thing
      get :event
    end
  end

  resources :skills do
    collection { post :sort }
  end

  resources :profiles
  resources :comments


  root "posts#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Four Athens Whiteboard</title>
  <%= favicon_link_tag (source='favicon.ico') %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:300,600,400' rel='stylesheet' type='text/css'>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to image_tag("/assets/fourathens.png", class: "navbar-brand brand-refine"), root_path %>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li class=" <%='active' if params[:controller] == 'posts'%>">
            <%= link_to "Whiteboard", root_path, class: "navlink", "data-no-turbolink" => true %>
          </li>
          <li class=" <%='active' if params[:controller] == 'profiles'%>">
            <%= link_to "Directory", directory_path, class: "navlink", "data-no-turbolink" => true %>
          </li>
          <% if current_user %>
            <% if can? :manage, Sheet, :user_id => current_user.id%>
              <li class="navlink <%='active' if params[:controller] == 'mentors'%>">
                <%= link_to "Mentor", mentors_path %>
              </li>
            <% end %>
          <% end %>
          <% if can? :update, User %>
            <li class="navlink <%='active' if params[:controller] == 'admin'%>">
              <%= link_to "Admin", admin_index_path %>
            </li>
          <% end %>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li class="dropdown">
              <a href="#" class="navlink dropdown-toggle" data-toggle="dropdown">Signed in as <%= current_user.first_name%> <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
                <li role="presentation"><a class="navlink"role="menuitem" tabindex="-1" href="/users/edit">User Settings</a></li>
                <li role="presentation">
                <%= link_to "User Profile", edit_profile_path(current_user.id),  class: "navlink", :role => "menuitem", :tabindex => "-1" %>
                </li>
                <% if current_user.admin? %>
                  <li role="presentation"><a href="/users/invitation/new" role="menuitem" tabindex="-1" class="navlink">Invite user</a></li>
                <% end %>
                <li role="presentation" class="divider"></li>
                <li role="presentation"><%= link_to "Log out", destroy_user_session_path, method: :delete, class: "navlink", role:"menuitem" %></li>
              </ul>
            </li >
          <% else %>
              <li><a class="navlink" data-toggle="modal" data-target="#SignInModal">Sign In</a></li>
              <li><a class="navlink" data-toggle="modal" data-target="#SignUpModal">Sign Up</a></li>
          <% end %>
        </ul >
      </div>
    </div>
  </nav>




<!-- Modal -->
<div class="modal fade" id="SignInModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">Sign In</h4>
      </div>
      <div class="modal-body">
        <%= render "devise/sessions/new"  %>
      </div>

    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="SignUpModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">Sign Up</h4>
      </div>
      <div class="modal-body">
        <%= render "devise/registrations/new"  %>
      </div>

    </div>
  </div>
</div>




  <%if notice %>
    <p class="notice alert alert-info"><%= notice %></p>
  <%end %>
  <%if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <%end %>

    <div class="container1">
      <%= yield %>
    </div>

  </body>
</html>